const tissues = {
  'Salmonella Typhimurium (LT2)': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Gallus gallus': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Xenopus laevis': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Dictyostelium discoideum': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Danio rerio': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Schizosaccharomyces pombe': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Escherichia coli (K12)': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Caenorhabditis elegans': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Saccharomyces cerevisiae': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Drosophila melanogaster': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Arabidopsis thaliana': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Mus musculus': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Homo sapiens': {
    cells: [
      '786O',
      'A-375',
      'A-498',
      'A-549',
      'ACHN',
      'BT-20',
      'BT-549',
      'BT549',
      'C10',
      'C106',
      'C32',
      'C75',
      'C80',
      'C84',
      'C99',
      'Caki-1',
      'CAL-27',
      'CaR-1',
      'CC07',
      'CC20',
      'CCK-81',
      'CCRF-CEM',
      'CoCM-1',
      'Colo 320DM',
      'Colo 741',
      'Colo-205',
      'Colo-678',
      'cycling crypt base columnar',
      'DLD-1',
      'DU-145',
      'EKVX',
      'GaMG',
      'GP2d',
      'HBL100',
      'HCA-46',
      'HCA-7',
      'HCC-1143',
      'HCC-1395',
      'HCC-1599',
      'HCC-1937',
      'HCC-202',
      'HCC-2218',
      'HCC-2998',
      'HCC-38',
      'HCC1143',
      'HCC1187',
      'HCC1569',
      'HCC1599',
      'HCC1806',
      'HCC1954',
      'HCC70',
      'HCT-116',
      'HCT-15',
      'HDC-111',
      'HDC-135',
      'HDC-142',
      'HDC-143',
      'HDC-54',
      'HDC-57',
      'HDC-73',
      'HDC-82',
      'HDC-9',
      'HEK-293',
      'HeLa',
      'Hep-G2',
      'HES-3',
      'HFE-145',
      'HL-60',
      'HMELonza',
      'HMEpC',
      'HMT-3522',
      'HOP-62',
      'HOP-92',
      'HRA-19',
      'Hs-578T',
      'HT-29',
      'HT55',
      'HTC-116',
      'IGROV-1',
      'JURKAT',
      'K-562',
      'KM-12',
      'LIM1863',
      'LNCaP',
      'LoVo',
      'LOX-IMVI',
      'LS-180',
      'LS1034',
      'LS123',
      'LS411',
      'LS513',
      'M14',
      'MALME-3M',
      'MCF-10A',
      'MCF-7',
      'MCF-7/adr',
      'MCF12A',
      'MDA-MB-157',
      'MDA-MB-231',
      'MDA-MB-435',
      'MDA-MB-436',
      'MDA-MB-453',
      'MDA-MB-468',
      'mesenchymal stromal',
      'MFM-223',
      'Mixed',
      'MO3_13',
      'MOLT-4',
      'NCI-H226',
      'NCI-H23',
      'NCI-H322M',
      'NCI-H460',
      'NCI-H522',
      'NCI-H548',
      'NCI-H716',
      'NCI-H747',
      'NCI/ADR-RES',
      'non-small cell lung cancer',
      'OVCAR-3',
      'OVCAR-4',
      'OVCAR-5',
      'OVCAR-8',
      'OVCAR-8/ADR',
      'OXCO-1',
      'OXCO-3',
      'pancreatic metastatic',
      'PC-3',
      'PC/JW',
      'RCC 786-O',
      'RCM-1',
      'RKO',
      'RPMI-8226',
      'RXF-393',
      'SF-268',
      'SF-295',
      'SF-539',
      'SK-CO-1',
      'SK-MEL-2',
      'SK-MEL-28',
      'SK-MEL-5',
      'SK-N-BE(2)',
      'SKOV-3',
      'SN-12C',
      'SNB-19',
      'SNB-75',
      'SNU-C2B',
      'SR',
      'SUM-159PT',
      'SUM1315',
      'SUM149',
      'SUM190',
      'SUM225',
      'SW-1116',
      'SW-403',
      'SW-48',
      'SW-480',
      'SW-620',
      'SW-948',
      'SW837',
      'T-47D',
      'T-84',
      'TK-10',
      'U-251 MG',
      'U-266/84',
      'U031',
      'U2-OS',
      'UACC-257',
      'UACC-62',
      'UO-31',
      'VACO 4A',
    ],
    tissues: [
      'adipocyte',
      'adipose tissue',
      'adrenal gland',
      'amniocyte',
      'aqueous humour',
      'arachnoid cyst',
      'B-lymphocyte',
      'blood platelet',
      'bone',
      'bone marrow',
      'bone marrow stromal',
      'brain',
      'breast',
      'breast cancer',
      'cardia',
      'carotid atherosclerotic plaque',
      'cerebral cortex',
      'cervical mucosa',
      'colon',
      'colon muscle',
      'colonic epithelial',
      'cytotoxic T-lymphocyte',
      'duodenum',
      'embryonic stem',
      'esophagus',
      'gall bladder',
      'gut',
      'hair follicle',
      'heart',
      'helper T-lymphocyte',
      'ileum epithelial',
      'kidney',
      'liver',
      'lung',
      'lymph node',
      'mesenchymal stem',
      'monocyte',
      'myometrium',
      'nasopharynx',
      'natural killer',
      'oral epithelium',
      'osteosarcoma',
      'ovary',
      'oviduct',
      'pancreas',
      'pancreatic islet',
      'placenta',
      'prefrontal cortex',
      'prostate gland',
      'rectum',
      'renal cell carcinoma',
      'retina',
      'salivary gland',
      'seminal vesicle',
      'skin',
      'small intestine',
      'smooth muscle',
      'spermatozoon',
      'spinal cord',
      'spleen',
      'stomach',
      'synovia',
      'testis',
      'thyroid gland',
      'tonsil',
      'ureter',
      'urinary bladder',
      'uterine cervix',
      'uterine endometrium',
      'uterus',
      'vermiform appendix',
      'vitreous humor',
    ],
  },
};

export default tissues;
