const tissues = {
  'Salmonella Typhimurium (LT2)': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Xenopus laevis': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Gallus gallus': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Danio rerio': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Dictyostelium discoideum': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Schizosaccharomyces pombe': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Escherichia coli (K12)': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Caenorhabditis elegans': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Drosophila melanogaster': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Saccharomyces cerevisiae': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Arabidopsis thaliana': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Mus musculus': {
    cells: [
    ],
    tissues: [
    ],
  },
  'Homo sapiens': {
    cells: [
      'A-431',
      'A549',
      'AF22',
      'AN3-CA',
      'ASC diff',
      'ASC TERT1',
      'BEWO',
      'BJ',
      'BJ hTERT+',
      'BJ hTERT+ SV40 Large T+',
      'BJ hTERT+ SV40 Large T+ RasG12V',
      'CACO-2',
      'CAPAN-2',
      'Daudi',
      'EFO-21',
      'fHDF/TERT166',
      'GAMG',
      'HaCaT',
      'HAP1',
      'HBEC3-KT',
      'HBF TERT88',
      'HDLM-2',
      'HEK 293',
      'HEL',
      'HeLa',
      'Hep G2',
      'HHSteC',
      'HL-60',
      'HMC-1',
      'HSkMC',
      'hTCEpi',
      'hTEC/SVTERT24-B',
      'hTERT-HME1',
      'hTERT-RPE1',
      'HUVEC TERT2',
      'JURKAT',
      'K-562',
      'Karpas-707',
      'LHCN-M2',
      'MCF7',
      'MOLT-4',
      'NB-4',
      'NTERA-2',
      'OE19',
      'PC-3',
      'REH',
      'RH-30',
      'RPMI-8226',
      'RPTEC TERT1',
      'RT4',
      'SCLC-21H',
      'SH-SY5Y',
      'SiHa',
      'SK-BR-3',
      'SK-MEL-30',
      'SuSa',
      'T-47d',
      'THP-1',
      'TIME',
      'U-138 MG',
      'U-2 OS',
      'U-2197',
      'U-251 MG',
      'U-266/70',
      'U-266/84',
      'U-698',
      'U-87 MG',
      'U-937',
      'WM-115',
    ],
    tissues: [
      'adipose tissue',
      'adrenal gland',
      'amygdala',
      'angular gyrus',
      'angular gyrus (white matter)',
      'anterior cingulate cortex, supragenual-dorsal',
      'anterior cingulate cortex, supragenual-ventral',
      'anterior cingulate gyrus, pregenual-dorsal',
      'anterior cingulate gyrus, pregenual-ventral',
      'anterior cingulate gyrus, subgenual',
      'anterior cochlear nucleus, ventral',
      'anterior funiculus (white matter)',
      'anterior insular cortex, dorsal',
      'anterior insular cortex, ventral',
      'anterior thalamic nucleus, ventral',
      'appendix',
      'arcuate nucleus',
      'area parastriata, inferior',
      'area parastriata, parietal',
      'area parastriata, superior',
      'area parastriata, temporal',
      'area postrema',
      'area striata',
      'area striata (white matter)',
      'basal amygdala',
      'bone marrow',
      'breast',
      'caudate nucleus',
      'central amygdala',
      'centromedial thalamic nucleus',
      'cerebellar cortex',
      'cerebellar nuclei',
      'cerebellar white matter',
      'cervical spinal cord, central gray',
      'cervical spinal cord, dorsal horn',
      'cervical spinal cord, ventral horn',
      'cervix',
      'choroid plexus',
      'claustrum',
      'colon',
      'corpus callosum, genu (white matter)',
      'corpus callosum, splenium (white matter)',
      'corticomedial amygdala',
      'cuneate nuclei',
      'cuneiform nucleus',
      'dentate gyrus',
      'dorsal cochlear nucleus',
      'dorsal funiculus (white matter)',
      'dorsal medullary reticular nucleus',
      'dorsal motor vagal complex',
      'dorsal raphe nucleus',
      'dorsal tegmental nucleus',
      'dorsolateral prefrontal cortex',
      'dorsolateral tegmental area',
      'dorsomedial nucleus',
      'dorsomedial prefrontal cortex',
      'duodenum',
      'endometrium',
      'entorhinal gyrus',
      'epididymis',
      'esophagus',
      'fallopian tube',
      'flocculonodular lobe',
      'frontal cortex',
      'frontal eye field',
      'frontal operculum',
      'frontomarginal cortex',
      'frontopolar cortex',
      'fusiform gyrus',
      'fusiform gyrus (white matter)',
      'gallbladder',
      'gigantocellular reticular nuclei, medullary',
      'gigantocellular reticular nuclei, pars',
      'globus pallidus, externus',
      'globus pallidus, internus',
      'gyrus rectus',
      'habenula',
      'heart muscle',
      'hippocampus',
      'hippocampus, CA1',
      'hippocampus, CA2',
      'hippocampus, CA3',
      'inferior colliculus',
      'inferior frontal gyrus, opercular',
      'inferior frontal gyrus, orbital',
      'inferior frontal gyrus, triangular',
      'inferior olive',
      'inferior parietal lobule',
      'inferior temporal gyrus',
      'intraparietal deep sulcus',
      'kidney',
      'Kolliker-Fuse nucleus',
      'lateral amygdala',
      'lateral funiculus (white matter)',
      'lateral geniculate body',
      'lateral hypothalamic area',
      'lateral lemniscal nuclei',
      'lateral medullary reticular nucleus',
      'lateral parabrachial nucleus',
      'lateral thalamic nuclei',
      'lateral vestibular nucleus',
      'lingual gyrus',
      'liver',
      'locus coeruleus',
      'lung',
      'lymph node',
      'mamillary body',
      'medial dorsal thalamic nucleus',
      'medial geniculate body',
      'medial olivary nucleus',
      'medial parabrachial nucleus',
      'medial periolivary nuclei',
      'medial vestibular nucleus',
      'median raphe nucleus',
      'middle cingulate cortex',
      'middle frontal gyrus',
      'middle temporal gyrus',
      'motor facial nucleus',
      'motor hypoglossal nucleus',
      'motor trigeminal nucleus',
      'nuclei of the trapezoid body',
      'nucleus accumbens',
      'nucleus ambiguus',
      'nucleus basalis of Meynert',
      'nucleus cuneatus',
      'nucleus gracilis',
      'nucleus of the diagonal band',
      'nucleus raphe magnus',
      'nucleus raphe obscurus',
      'nucleus raphe pallidus',
      'nucleus reuniens',
      'nucleus rhomboideus',
      'nucleus tractus solitarii',
      'occipital cortex',
      'occipital cortex (white matter)',
      'olfactory area',
      'olfactory tubercle',
      'orbitofrontal gyrus, anterior',
      'orbitofrontal gyrus, lateral',
      'orbitofrontal gyrus, medial',
      'orbitofrontal gyrus, posterior',
      'ovary',
      'pancreas',
      'paracentral lobule, anterior',
      'paracentral lobule, posterior',
      'parahippocampal cortex',
      'parahippocampal cortex (white matter)',
      'paramedian reticular nucleus',
      'parathyroid gland',
      'paraventricular nucleus',
      'parietal cortex',
      'parietal operculum',
      'parieto-insular cortex',
      'parieto-occipital transitional area',
      'parieto-temporal junction (white matter)',
      'parvicellular reticular nuclei',
      'parvicellular reticular nuclei, medullary',
      'pedunculopontine tegmental nucleus',
      'periaquaductal grey, anterior',
      'periaquaductal grey, dorsal',
      'periaquaductal grey, lateral',
      'perirhinal gyrus',
      'peritrigeminal nucleus',
      'piriform cortex',
      'placenta',
      'pontine nuclei',
      'pontine raphe nucleus',
      'postcentral gyrus',
      'postcentral gyrus, dorsal',
      'postcentral gyrus, middle',
      'postcentral gyrus, ventral',
      'posterior cingulate cortex',
      'posterior cingulate cortex, dorsal',
      'posterior cingulate cortex, ventral',
      'posterior insular cortex',
      'posterior thalamic nucleus',
      'posteroventral cochlear nucleus',
      'precentral gyrus',
      'precentral gyrus, dorsal',
      'precentral gyrus, middle',
      'precentral gyrus, ventral',
      'precuneus',
      'premotor cortex, dorsal',
      'premotor cortex, ventral',
      'preoptic area',
      'prepositus hypoglossal nucleus',
      'pretectal area',
      'principal sensory trigeminal nucleus',
      'prostate',
      'pulvinar',
      'putamen',
      'rectum',
      'red nucleus',
      'reticular pontine nucleus, caudal',
      'reticular pontine nucleus, oral',
      'reticulotegmental nucleus',
      'retrosplenial cortex',
      'salivary gland',
      'seminal vesicle',
      'septal nuclei',
      'skeletal muscle',
      'skin',
      'small intestine',
      'smooth muscle',
      'somatomor cortex, precentral gyrus (white matter)',
      'somatosensory cortex, postcentral gyrus, ventral (white matter)',
      'spinal trigeminal nucleus, caudal',
      'spinal trigeminal nucleus, interpolar',
      'spinal trigeminal nucleus, oral',
      'spinal vestibular nucleus',
      'spleen',
      'stomach',
      'stria terminalis, bed nucleus',
      'subcallosal gyrus',
      'subcentral gyrus, S2',
      'subcoeruleus area',
      'subiculum',
      'substantia nigra',
      'subthalamic nucleus',
      'superior colliculus',
      'superior frontal gyrus',
      'superior olive',
      'superior parietal lobule',
      'superior temporal gyrus',
      'superior vestibular nucleus',
      'supplementary motor cortex',
      'suprachiasmatic nucleus',
      'supramarginal gyrus',
      'supraoptic nucleus',
      'temporal cortex',
      'temporal cortex (white matter)',
      'temporal pole',
      'temporal white matter',
      'temporo-insular cortex, parainsular gyrus',
      'temporo-occipital transitional zone',
      'testis',
      'thymus',
      'thyroid gland',
      'tongue',
      'tonsil',
      'transversal temporal gyrus, anterior',
      'transversal temporal gyrus, posterior',
      'urinary bladder',
      'ventral medullary reticular nucleus',
      'ventral periolivary nuclei',
      'ventral posterolateral thalamic nucleus',
      'ventral posteromedial thalamic nucleus',
      'ventral tegmental area',
      'ventral thalamic nuclei',
      'ventrolateral medulla, A1/C1 cell groups',
      'ventrolateral prefrontal cortex',
      'ventrolateral tegmental area, A5 NE cell group',
      'ventromedial nucleus',
      'ventromedial prefrontal cortex',
      'vermis',
      'zona incerta',
    ],
  },
};

export default tissues;
